### PR TITLE
Update pt_BR and es translations, add es_US, es_MX

### PR DESCRIPTION
**Pull request by hadess**
The Mega Drive is called “Mega Drive” everywhere but in Canada, the US and Mexico, should be changed to say "Mega Drive" rather than "Genesis" for all those territories in question.

The description for the object itself isn't "a compatibility layer" but an emulator (“Emulador” in both Spanish and Portuguese).

### CODE REVIEW

**Comment by alice-mkh** [comment]
Thanks, this indeed looks more correct.

**Comment by alice-mkh** [comment]
Though really it still seems to miss the word "fast", but it's not super important. We really need a proper translator review somehow.

**Comment by hadess** [comment]
I just realised that the first translation also dropped the word "fast"...

**Comment by hadess** [comment]
> Though really it still seems to miss the word "fast", but it's not super important. We really need a proper translator review somehow.

Yes. Maybe you should move those metainfo files upstream, and if you can't, maybe to GNOME infrastructure?

**Comment by alice-mkh** [comment]
I wonder how we would get it here from the upstream repo though, as we don't build it here. Just sync it manually from time to time?

**Comment by alice-mkh** [comment]
https://gitlab.gnome.org/GNOME/gnome-games/issues/244

**Comment by hadess** [comment]
You can reference the file directly, something like:
```
                {
                    "type": "file",
                    "url": "https://helpx.adobe.com/content/dam/help/mnemonics/flashplayer_app_RGB.svg",
                    "sha256": "97fc022ae65f37a2e36d6be71c651dbd3d2f7c82f9f89ba13ea3e6cf9be3144c",
                    "dest-filename": "com.adobe.Flash-Player-Projector.svg"
                },
```

**Comment by alice-mkh** [comment]
But the file would be an untranslated placeholder then. Though it's probably possible to generate the translated file here from the `*.metainfo.in` and `po/` when building the extension.

**Comment by hadess** [comment]
> But the file would be an untranslated placeholder then. Though it's probably possible to generate the translated file here from the `*.metainfo.in` and `po/` when building the extension.

Export a file with the translations merged in, in the CI?

**Pull request merged**
