### PR TITLE
Add translation pt_BR and es

### PR DESCRIPTION
**Pull request by LeandroStanger**

### CODE REVIEW

**Comment by alice-mkh** [comment]
LGTM, thanks!

**Comment by Kekun** [comment]
I think the names aren't good, as AFAIK:
- in Spanish speaking America the North American names are used
- in Spain the Europeans names are used
- in Portugal and Brasil the European names are used

This MR uses the North America names for all Spanish and for Brasilian Protuguese, which doesn't seem right. We'd need knowledgeable locals to translate that accurately. :)

Unless of course I'm wrong, then I'd love to learn something.

**Comment by hadess** [comment]
The Mega Drive is called that everywhere but in Canada, the US and Mexico, so this should be changed to say "Mega Drive" rather than "Genesis".

Also, the description for the object isn't "a compatibility layer" but an emulator (“Emulador” in both Spanish and Portuguese).

**Comment by alice-mkh** [comment]
Meh. Reverted, thanks. :(

**Comment by alice-mkh** [comment]
The fact the translation is directly here at all is already very much non-ideal. I wonder if this file can be somehow hosted upstream like the main appdata.

**Comment by hadess** [comment]
I created https://github.com/flathub/org.gnome.Games.LibretroPlugin.PicoDrive/pull/4 on top of this code, before the revert.

**Pull request merged**
